version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: rental_db
    environment:
      POSTGRES_USER: rental
      POSTGRES_PASSWORD: rental123
      POSTGRES_DB: rentaldb
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data:
